// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcNbjYV_2KdRyx3rADpT9btbwoLHBvh30',
    appId: '1:1030891610206:web:4018cf33478a028d9894cf',
    messagingSenderId: '1030891610206',
    projectId: 'itti-2b139',
    authDomain: 'itti-2b139.firebaseapp.com',
    storageBucket: 'itti-2b139.firebasestorage.app',
    measurementId: 'G-ZSPCVRJ4XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Uc2X96FY7q-hpS91wATVHl1ednggH4E',
    appId: '1:1030891610206:android:74cbf5c16ce23b9c9894cf',
    messagingSenderId: '1030891610206',
    projectId: 'itti-2b139',
    storageBucket: 'itti-2b139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB64y5NiCXwrfACtsbsUHuEUjtAdlYpMDI',
    appId: '1:1030891610206:ios:bdee5b4fd32c5bd69894cf',
    messagingSenderId: '1030891610206',
    projectId: 'itti-2b139',
    storageBucket: 'itti-2b139.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB64y5NiCXwrfACtsbsUHuEUjtAdlYpMDI',
    appId: '1:1030891610206:ios:bdee5b4fd32c5bd69894cf',
    messagingSenderId: '1030891610206',
    projectId: 'itti-2b139',
    storageBucket: 'itti-2b139.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcNbjYV_2KdRyx3rADpT9btbwoLHBvh30',
    appId: '1:1030891610206:web:147ae5aec69b5b799894cf',
    messagingSenderId: '1030891610206',
    projectId: 'itti-2b139',
    authDomain: 'itti-2b139.firebaseapp.com',
    storageBucket: 'itti-2b139.firebasestorage.app',
    measurementId: 'G-GLE1M426W0',
  );
}
